from flask import Flask, render_template, jsonify, request
import firebase_admin
from firebase_admin import credentials, db
import json
from datetime import datetime
import os
import sys

app = Flask(__name__)

# --- CONFIGURATION ---
# Use the exact database URL from your desktop POS application
FIREBASE_DATABASE_URL = 'https://heriwadi-bookshop-default-rtdb.firebaseio.com'

# Initialize Firebase
try:
    # 1. Securely load credentials from the environment variable (Required for Render)
    cred_json_str = os.environ.get('FIREBASE_CREDENTIALS_JSON')
    
    if cred_json_str:
        # Load the JSON string into a dictionary
        cred_info = json.loads(cred_json_str)
        # Use the dictionary content for credentials
        cred = credentials.Certificate(cred_info)
        
        firebase_admin.initialize_app(cred, {
            'databaseURL': FIREBASE_DATABASE_URL
        })
        print("✅ Firebase initialized successfully from Environment Variable.")
        
    else:
        # This block executes if the environment variable is missing on Render
        print("⚠️ FIREBASE_CREDENTIALS_JSON environment variable not found.")
        print("🔴 Dashboard will fail to fetch live data. Please check Render configuration.")
        sys.exit(1) 
        
except Exception as e:
    # This block executes if there's a parsing error in the JSON or a connection issue
    print(f"❌ Firebase initialization failed: {e}")
    sys.exit(1)

# --- FLASK ROUTES ---

@app.route('/')
def dashboard():
    """Renders the main dashboard HTML template. Corrected to use index.html."""
    return render_template('index.html')

@app.route('/api/sales')
def get_sales():
    """Fetches and formats recent sales for the activity feed."""
    try:
        ref = db.reference('/sales')
        # Limit to the last 50 sales
        sales_data = ref.order_by_child('timestamp').limit_to_last(50).get()
        
        if sales_data:
            sales = []
            for key, value in sales_data.items():
                sales.append({
                    'id': value.get('sale_id', ''),
                    'amount': value.get('total_amount', 0),
                    'payment_method': value.get('payment_method', ''),
                    'timestamp': value.get('timestamp', ''),
                    'items_count': len(value.get('items', []))
                })
            return jsonify(sales[::-1])  # Reverse to show latest first
    except Exception as e:
        print(f"Error fetching sales: {e}")
    
    return jsonify([])

@app.route('/api/stats')
def get_stats():
    """Calculates and returns total sales, transactions, and today's sales (Robust Date Check)."""
    try:
        ref = db.reference('/sales')
        sales_data = ref.get()
        
        if sales_data:
            total_sales = 0.0
            total_transactions = 0
            today_sales = 0.0
            
            # Get today's date once
            today = datetime.now().date()
            
            for sale in sales_data.values():
                total_amount = sale.get('total_amount', 0)
                timestamp_str = sale.get('timestamp')

                # Calculate cumulative totals
                total_sales += total_amount
                total_transactions += 1
                
                # Robust calculation for Today's sales
                if timestamp_str:
                    try:
                        # Use fromisoformat which handles the format generated by main.py
                        sale_date = datetime.fromisoformat(timestamp_str).date()
                        if sale_date == today:
                            today_sales += total_amount
                    except ValueError:
                        # This catches improperly formatted timestamps, ensuring the loop continues.
                        print(f"Warning: Could not parse timestamp '{timestamp_str}'.")
            
            return jsonify({
                'total_sales': total_sales,
                'total_transactions': total_transactions,
                'today_sales': today_sales
            })
    except Exception as e:
        print(f"Error fetching stats: {e}")
    
    # Return default zero values on failure
    return jsonify({
        'total_sales': 0,
        'total_transactions': 0,
        'today_sales': 0
    })

@app.route('/api/recent-activity')
def get_recent_activity():
    """Fetches and formats the 10 most recent activities."""
    try:
        ref = db.reference('/sales')
        sales_data = ref.order_by_child('timestamp').limit_to_last(10).get()
        
        if sales_data:
            activity = []
            for key, value in sales_data.items():
                activity.append({
                    'type': 'sale',
                    'message': f"Sale #{value.get('sale_id', '')} - KES {value.get('total_amount', 0):.2f}",
                    'timestamp': value.get('timestamp', '')
                })
            return jsonify(activity[::-1]) # Reverse to show latest first
    except Exception as e:
        print(f"Error fetching activity: {e}")
    
    return jsonify([])

if __name__ == '__main__':
    # Use 0.0.0.0 and dynamically set PORT for Render deployment compatibility
    app.run(debug=True, host='0.0.0.0', port=os.environ.get('PORT', 5000))
